
server:
  port: 8087

spring:
  datasource:
    url:  jdbc:postgresql://localhost:5433/portalegressodb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
      default_schema: egresso
      jdbc:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
