
server:
  port: 8087
spring:
  datasource:
    url:  jdbc:postgresql://localhost:5433/portalegressodb
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      default_schema: egresso
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      jdbc:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        lob.non-contextual-creation: true
    properties:
      hibernate:
        show_sql: true
